### ISSUE TITLE
Needs front end 'tcp_request' custom resource propery defined for SSL front end inspection

### ISSUE THREAD

**Issue by TitaniumNerd** [sous-chefs/haproxy#283] opened 2018-02-27 16:30 UTC
### Cookbook version
5.0.3

### Chef-client version
13.6.4

### Platform Details
Windows 10 build 1607

### Scenario:
Need to apply content inspection for frontends.

Would request that the resource property tcp_request be also applied as an array property for front end configurations to allow for SSL content inspection prior to handing the request to the back end.  

Example update request:

#Add the following to frontend.rb resource.
property :tcp_request, Array

#Add the following to frontend.rb resource.
      variables['frontend'][new_resource.name]['tcp_request'] ||= [] unless new_resource.tcp_request.nil?
      variables['frontend'][new_resource.name]['tcp_request'] << new_resource.tcp_request unless new_resource.tcp_request.nil?

Have confirmed that rules apply if these edits are performed to the frontend.rb to allow for tcp_request properties in the frontend.rb resource.

### Steps to Reproduce:
haproxy_frontend node['example']['config'] do
    tcp_request [
        'inspect-delay 1s,
        'content accept if { req_ssl_hello_type 1 }'
]
    use_backend blah blah if host blah
end
### Expected Result:
Applied tcp_request rules for the front end config of an HA Proxy file for basic SSL inspection.

### Actual Result:
ERROR: undefined method 'tcp_request' for Custom resource haproxy_frontend from cookbook haproxy

**Comment by rshade** [comment] 2018-02-27 16:48
can you use the `:extra_options` hash?

**Comment by TitaniumNerd** [comment] 2018-02-27 16:57
I have tried.  It accepts only the first input for tcp_request and disregards any secondary inputs.  In the example above, it would allow 'inspect-delay 1s', but would disregard 'content accept if { req_ssl_hello_type 1 }' since it is a hash value and not an array.  If I enter extra options values twice, it will accept the first input only.  If I enter the name value for tcp_request, it fails to accept anything more than the first input.  This value is best served as an array item.  I can alter the property in the cookbook for extra options and change it to an array and it will accept this input and works that way.

**Comment by rshade** [comment] 2018-02-27 16:58
can you send me your extra_options code?

**Comment by TitaniumNerd** [comment] 2018-02-27 17:03
extra_options(
    'tcp_request' => [
      'content inspect-delay 1s',
      'content accept if { req_ssl_hello_type 1 }',
    ])

**Comment by rshade** [comment] 2018-02-27 18:45
Thank you I will write a test around that and see what I get.

**Comment by mengesb** [comment] 2018-08-20 21:46
```ruby
extra_options 'tcp-request content inspect-delay' => '1s',
              'tcp-request content accept' => 'if { req_ssl_hello_type 1 }'
```

Wouldn't this work?

**Comment by c240amg** [comment] 2018-08-20 23:35
I have the same issue, even with extra_options, it only works for the first input. Subsequent input (with the same option (tcp-request) is ignored.
So in the case that mengesb shows, only the inspect-delay would show in the config, the content accept doesn't

**Comment by syndesis** [comment] 2018-08-21 15:47
@c240amg the key portion of the hash needs to be unique as @mengesb suggested above.  Just add enough data to it to make it so.  Confirmed that this works:
```
extra_options(
    'tcp-request inspect-delay' => '1s',
    'tcp-request content accept' => 'if { req_ssl_hello_type 1 }'
 )
```

**Comment by mengesb** [comment] 2018-08-23 08:09
Are we OK to close this out; or would you like to see more work on this front @TitaniumNerd ?

@rshade -- there might be some scenarios where we can't make a unique key out of that. Does our current implementation of `extra_options` support empty values for the hash? Not sure if there's a situation where that'd be the case; looks like not - following https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4-tcp-request%20content

i.e.
```ruby
extra_options(
    'tcp-request inspect-delay 1s' => '',
    'tcp-request content accept if { req_ssl_hello_type 1 }' => ''
 )
```

**Comment by rshade** [comment] 2018-08-23 14:15
We can possibly add tcp-request as a top level item if we need to support multiple empty hashes. Sorry for the delay on this ticket.

**Comment by damacus** [comment] 2018-10-09 08:11
Closing this down as it's supported by the additional_options hash.  If we need an example of this working I'll add one to the rspec tests.

**Closed by damacus** 2018-10-09 08:11 UTC
